runtime: python39
entrypoint: gunicorn -w 1 otp_datastore:app

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /libopenmpt.js.mem
  static_files: libopenmpt.js.mem
  upload: libopenmpt.js.mem
- url: /.*
  secure: optional
  script: auto
