runtime: python27
api_version: 1
threadsafe: yes
service: datastore

libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest

handlers:
- url: /.*
  script: otp_datastore.app
  login: optional